language: node_js
node_js: '16'
install: true
before_script: 
  - npm ci
script: 
  - npm run build
  - cp CNAME build/CNAME
branches:
  only:
    - source
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    target_branch: master
    on:
      branch: source
