name: Release

on:
    push:
        branches: [source]

jobs:
    publish:
        name: Analyze
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'npm'
                  cache-dependency-path: 'package-lock.json'
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: |
                  npm run build
                  cp CNAME build/CNAME
            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: build
                  branch: master
